import { createRecipe } from "./recipe-utils";

export const recipes = [
  createRecipe({
    title: "MOA MANU",
    category: "Bowl",
    items: [
      { name: "Ris", amount: "215 g" },
      { name: "Teriyaki", amount: "15 g" },
      { name: "Mango", amount: "50 g" },
      { name: "Sojabönor (edamame)", amount: "15 g" },
      { name: "Gurka", amount: "35 g" },
      { name: "Picklad rödkål", amount: "35 g" },
      { name: "Rödbets gari", amount: "20 g" },
      { name: "Sojamajonnäs", amount: "40 g" },
      { name: "Solrostopping", amount: "15 g" },
      { name: "Cashewnötter", amount: "10 g" },
      { name: "Koriander", amount: "5 g" },
      { name: "Furikake", amount: "40 g" },
    ],
  }),
  createRecipe({
    title: "HEY BAY",
    category: "Bowl",
    items: [
      { name: "Ris", amount: "215 g" },
      { name: "Teriyaki", amount: "15 g" },
      { name: "Mango", amount: "50 g" },
      { name: "Sojabönor (edamame)", amount: "15 g" },
      { name: "Morot kimchi-marinerad", amount: "60 g" },
      { name: "Rödbets gari", amount: "20 g" },
      { name: "Chilimajonnäs", amount: "40 g" },
      { name: "Kokostopping", amount: "15 g" },
      { name: "Cashewnötter", amount: "10 g" },
      { name: "Koriander", amount: "5 g" },
      { name: "Furikake", amount: "50 g" },
    ],
  }),
  createRecipe({
    title: "SASSY CAESAR",
    category: "Sallad",
    items: [
      { name: "Romansallad", amount: "100 g" },
      { name: "Vitkål", amount: "50 g" },
      { name: "Grönkål", amount: "20 g" },
      { name: "Quinoa", amount: "90 g" },
      { name: "Caesardressing", amount: "20 g" },
      { name: "Picklad rödkål", amount: "45 g" },
      { name: "Frötopping", amount: "20 g" },
      { name: "Grana Padano", amount: "10 g" },
    ],
  }),
  createRecipe({
    title: "THE OG",
    category: "Sallad",
    items: [
      { name: "Vitkål", amount: "70 g" },
      { name: "Grönkål", amount: "40 g" },
      { name: "Picklad rödkål", amount: "30 g" },
      { name: "Gomadressing", amount: "50 g" },
      { name: "Sojabönor", amount: "20 g" },
      { name: "Kokostopping", amount: "10 g" },
      { name: "Rostad schalottenlök", amount: "10 g" },
      { name: "Furikake", amount: "50 g" },
      { name: "Salladslök", amount: "5 g" },
    ],
  }),
  createRecipe({
    title: "BIMBIMBAP",
    category: "Bowl",
    items: [
      { name: "Osötat ris", amount: "200 g" },
      { name: "Spetskål", amount: "50 g" },
      { name: "Entrecote", amount: "100 g" },
      { name: "Niku glaze", amount: "7 g" },
      { name: "Chilimayo", amount: "35 g" },
      { name: "Gochujang dressing", amount: "7 g" },
      { name: "Picklad rödlök", amount: "25 g" },
      { name: "Picklad sesamgurka", amount: "25 g" },
      { name: "Picklad gari", amount: "20 g" },
    ],
  }),
  createRecipe({
    title: "MINI KALE CAESAR",
    category: "Sallad",
    items: [
      { name: "Romansallad", amount: "35 g" },
      { name: "Vitkål", amount: "10 g" },
      { name: "Grönkål", amount: "15 g" },
      { name: "Quinoa", amount: "30 g" },
      { name: "Caesardressing", amount: "25 g" },
      { name: "Frötopping", amount: "10 g" },
    ],
  }),
  createRecipe({
    title: "TRIPLE CHEESE",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "70 g" },
      { name: "Mayo", amount: "15 g" },
      { name: "Senap", amount: "8 g" },
      { name: "Pickles", amount: "15 g" },
      { name: "Cheddar", amount: "39 g" },
      { name: "Mayo topping", amount: "15 g" },
      { name: "Ketchup", amount: "15 g" },
      { name: "Silverlök", amount: "25 g" },
    ],
  }),
  createRecipe({
    title: "TRYFFEL",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "50 g" },
      { name: "Tryffelmayo", amount: "15 g" },
      { name: "Rostad schalottenlök", amount: "12 g" },
      { name: "Pickles", amount: "15 g" },
      { name: "Cheddar", amount: "26 g" },
      { name: "Tryffelmayo topping", amount: "20 g" },
      { name: "Silverlök", amount: "25 g" },
    ],
  }),
  createRecipe({
    title: "ORIGINALEN",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "50 g" },
      { name: "Vitlöksmayo", amount: "15 g" },
      { name: "Tomat", amount: "30 g" },
      { name: "Rostad schalottenlök", amount: "12 g" },
      { name: "Cheddar", amount: "26 g" },
      { name: "Vitlöksmayo topping", amount: "15 g" },
      { name: "Krisp sallad", amount: "15 g" },
    ],
  }),
  createRecipe({
    title: "SMOKEY CHILI",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "50 g" },
      { name: "Chipotlemayo", amount: "15 g" },
      { name: "Rostad schalottenlök", amount: "12 g" },
      { name: "Krispsallad", amount: "15 g" },
      { name: "Cheddar", amount: "26 g" },
      { name: "Bacon", amount: "20 g" },
      { name: "BBQ", amount: "6 g" },
    ],
  }),
  createRecipe({
    title: "KILLIN KENTUCKY",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "70 g" },
      { name: "Chilimayo", amount: "15 g" },
      { name: "Protein", amount: "100 g" },
      { name: "Silverlök", amount: "25 g" },
      { name: "Sweet chili", amount: "30 g" },
      { name: "Rostad schalottenlök", amount: "12 g" },
      { name: "Koriander", amount: "5 g" },
    ],
  }),
  createRecipe({
    title: "CHILI ZEPHYR",
    category: "Burger",
    items: [
      { name: "Bröd", amount: "50 g" },
      { name: "Chili-bearnaise", amount: "20 g" },
      { name: "Kött", amount: "200 g" },
      { name: "Cheddar", amount: "26 g" },
      { name: "Chili-bearnaise topping", amount: "15 g" },
      { name: "Silverlök", amount: "25 g" },
    ],
  }),
  createRecipe({
    title: "TACOS DE POLLO FRITO",
    category: "Taco",
    items: [
      { name: "Tortillabröd", amount: "27 g" },
      { name: "Chilimayo", amount: "10 g" },
      { name: "Ananas salsa", amount: "17 g" },
      { name: "Panerad kyckling", amount: "50 g" },
      { name: "Koriander", amount: "3 g" },
      { name: "Limeklyfta", amount: "15 g" },
    ],
  }),
  createRecipe({
    title: "TALLOUMI TACO",
    category: "Taco",
    items: [
      { name: "Tortillabröd", amount: "27 g" },
      { name: "Chilimayo", amount: "15 g" },
      { name: "Mango", amount: "25 g" },
      { name: "Panoumi", amount: "45 g" },
      { name: "Picklad rödlök", amount: "10 g" },
      { name: "Picklad jalapeño", amount: "5 g" },
      { name: "Smulad feta", amount: "5 g" },
      { name: "Hackad koriander", amount: "3 g" },
      { name: "Lime", amount: "15 g" },
    ],
  }),
  createRecipe({
    title: "BAJA FISH",
    category: "Taco",
    items: [
      { name: "Tortillabröd", amount: "27 g" },
      { name: "Picklad rödkål", amount: "20 g" },
      { name: "Panerad fisk", amount: "60 g" },
      { name: "Chilimayo", amount: "10 g" },
      { name: "Rostad lök", amount: "5 g" },
      { name: "Hackad koriander", amount: "5 g" },
      { name: "Lime", amount: "15 g" },
    ],
  }),
  createRecipe({
    title: "CARNITAS",
    category: "Taco",
    items: [
      { name: "Tortillabröd", amount: "27 g" },
      { name: "Guacamole", amount: "7 g" },
      { name: "Ananassalsa", amount: "17 g" },
      { name: "Fläsk", amount: "45 g" },
      { name: "Chipotle mayo", amount: "5 g" },
      { name: "Koriander", amount: "3 g" },
      { name: "Lime", amount: "15 g" },
    ],
  }),
  createRecipe({
    title: "BAOLLOUMI",
    category: "Bao",
    items: [
      { name: "Bao bröd", amount: "40 g" },
      { name: "Panko pannoumi", amount: "60 g" },
      { name: "Chilimayo", amount: "15 g" },
      { name: "Picklad rödkål", amount: "20 g" },
      { name: "Fetaost", amount: "10 g" },
      { name: "Koriander", amount: "5 g" },
    ],
  }),
  createRecipe({
    title: "KOREAN FRIED CHICKEN BAO",
    category: "Bao",
    items: [
      { name: "Bao bröd", amount: "40 g" },
      { name: "Chilimayo", amount: "15 g" },
      { name: "KFC chicken", amount: "50 g" },
      { name: "Korean glaze", amount: "5 g" },
      { name: "Picklad rödlök", amount: "20 g" },
      { name: "Sesampicklad gurka", amount: "15 g" },
      { name: "Koriander", amount: "5 g" },
    ],
  }),
  createRecipe({
    title: "GARLIC FRIES",
    category: "Sides",
    items: [
      { name: "Fries", amount: "160 g" },
      { name: "Vitlöksolja", amount: "10 g" },
      { name: "Parmesanmix", amount: "20 g" },
    ],
  }),
  createRecipe({
    title: "FISH STICKS",
    category: "Sides",
    items: [
      { name: "Panerad fisk", amount: "120 g" },
      { name: "Lime", amount: "15 g" },
      { name: "Chilimayo", amount: "50 g" },
    ],
  }),
  createRecipe({
    title: "FRIED UMAMI BROCCOLI",
    category: "Sides",
    items: [
      { name: "Broccoli", amount: "150 g" },
      { name: "Umami BBQ", amount: "50 g" },
      { name: "Salladslök", amount: "10 g" },
      { name: "Rostad lök", amount: "10 g" },
    ],
  }),
  createRecipe({
    title: "CRISPY DUMPLINGS",
    category: "Sides",
    items: [
      { name: "Dumplings", amount: "132 g" },
      { name: "Hackad koriander", amount: "3 g" },
      { name: "Soja", amount: "30 g" },
    ],
  }),
  createRecipe({
    title: "CHICKEN STICKS",
    category: "Sides",
    items: [
      { name: "KFC sticks", amount: "45 g" },
      { name: "Parmesan persilja", amount: "7 g" },
      { name: "Korean BBQ", amount: "30 g" },
    ],
  }),
  createRecipe({
    title: "FISH N FRIES",
    category: "Sides",
    items: [
      { name: "Panerad fisk", amount: "100 g" },
      { name: "Fries", amount: "150 g" },
      { name: "Picklad rödkål", amount: "40 g" },
      { name: "Ketchup dipp", amount: "30 g" },
    ],
  }),
  createRecipe({
    title: "GURKSALSA",
    category: "Sås",
    items: [
      { name: "Honung", amount: "4 dl" },
      { name: "Sesamolja", amount: "3 dl" },
      { name: "Soja", amount: "3 l" },
      { name: "Suehiro vinäger", amount: "6 dl" },
      { name: "Rapsolja", amount: "2 l" },
      { name: "Gochugaru", amount: "3 dl" },
      { name: "Vitlök", amount: "125 g" },
    ],
    notes: "Batchrecept med blandade måttenheter.",
  }),
  createRecipe({
    title: "JORDNÖTSMAYO",
    category: "Sås",
    items: [
      { name: "Jordnötssmör", amount: "1050 g" },
      { name: "Riven vitlök", amount: "70 g" },
      { name: "Socker", amount: "1.5 dl" },
      { name: "Majonnäs", amount: "5 l" },
      { name: "Soja", amount: "5 dl" },
      { name: "Pressad lime", amount: "4 st" },
      { name: "Salt", amount: "5-10 g" },
    ],
    notes: "Batchrecept med blandade måttenheter.",
  }),
];
